# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["*"]
    tags: ["*"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  MAIN_FILE: assignment

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: cristiangreco/pdflatex

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run pdflatex
        run: |
          apk add --no-cache make || (apt-get update && apt-get install -y make)
          make

      # Runs a set of commands using the runners shell
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        if: github.ref_type != 'tag'
        with:
          name: pdf file
          path: "build/${{ env.MAIN_FILE }}.pdf"
      - name: create release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            build/${{ env.MAIN_FILE }}.pdf
